### ISSUE TITLE
SetResult doesn't move Setting to Voting

### ISSUE THREAD

**Issue by chrisli30** [bodhiproject/bodhi-api#13]
the topic “MingJie’s bet: am I handsome” I set during meeting hasn’t gone from Setting to Voting stage.

@dwalintukan  could you test this flow a couple of times to make sure it will constantly succeed?

Even better if you can show us how to use api to verify results, like the traces you showed me today calling "/getresults", so we can learn how to identify the problem? Don't need a good write-up,  success traces should be enough.

**Comment by dwalintukan** [comment]
My guess is you didn't actually get to set result because you left the page before the approve got back. Once the approve comes back successfully (while you are still on the setting page), and the long polling checks the allowance that matches the consensus threshold. Then it will call setResult after.

Here is how the logic works for approve > setResult:
1. There is a constant timer that executes logic based on a flag `checkingAllowance` when you go into the oracle detail page. This flag starts as false.
2. When you click the button to set the result, it switches the `checkingAllowance` to true which will then start calling /allowance.
3. On the first /allowance return, most likely your allowance will be 0 for this TopicEvent. So it will call /approve for 100 BOT.
4. At the same time, it is still constantly calling /allowance. Once the /approve goes through and the /allowance returns as 100 BOT, it will execute the /setresult now.
5. In the demo, you left the oracle detail page before the /allowance came back and called /setresult. My long polling only works while you are still on the detail page. When you leave it stops.

For the MVP and as we discussed with TT, it would be optimal if we saved this somewhere in the DB or in the local file structure. This requires some changes that I will go over tomorrow.
